{
    "name": "Emdad Design",
    "version": "17.0.1.0.0",
    "category": "Themes/Backend",
    "summary": "Emdad Layout & Design",
    "description": """Minimalist and elegant theme for emdad backend""",
    "author": "Emdad",
    "company": "Emdad",
    "maintainer": "Hamilton Tech",
    "website": "https://www.hst.jo",
    "depends": ["web"],
    "data": [
        "views/layout_templates.xml",
        "views/base_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "code_backend_theme/static/src/xml/settings_templates.xml",
            "code_backend_theme/static/src/xml/top_bar_templates.xml",
            "code_backend_theme/static/src/scss/theme_accent.scss",
            "code_backend_theme/static/src/scss/navigation_bar.scss",
            "code_backend_theme/static/src/scss/datetimepicker.scss",
            "code_backend_theme/static/src/scss/theme.scss",
            "code_backend_theme/static/src/scss/sidebar.scss",
            "code_backend_theme/static/src/js/chrome/sidebar_menu.js",
            "code_backend_theme/static/src/js/fields/colors.js",
        ],
        "web.assets_frontend": [
            "code_backend_theme/static/src/scss/login.scss",
        ],
    },
    "images": [
        "static/description/banner.png",
        "static/description/theme_screenshot.png",
    ],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": False,
    "pre_init_hook": "test_pre_init_hook",
    "post_init_hook": "test_post_init_hook",
}
